font_family        Mononoki Nerd Font
font_size 17.0
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 Symbols Nerd Font Mono

scrollbar_handle_color #414B50

url_color #0087bd
url_style straight

tab_bar_style powerline
tab_powerline_style angled

active_tab_foreground   #131229
active_tab_background   #1184a3
active_tab_font_style   bold
inactive_tab_foreground #1184a3
inactive_tab_background #131229
inactive_tab_font_style normal

background #272E33
foreground #D3C6AA
selection_background #374145
selection_foreground #A7C080
background_opacity 1 


 color0 #4F5B58
 color8 #414B50

#: black

 color0 #4F5B58
 color8 #414B50

#: red

 color1 #E67E80
 color9 #4C3743

#: green

 color2  #A7C080
 color10 #3C4841

#: yellow

 color3  #DBBC7F
 color11 #45443C

#: blue

 color4  #7FBBB3
 color12 #384B55

#: magenta

 color5  #D699B6
 color13 #62445A

#: cyan

 color6  #83C092
 color14 #3D5746

#: white

 color7  #D3C6AA
 color15 #7A8478
