; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[Spotify]
accent             = A7C080
accent-active      = A7C080
accent-inactive    = 3C4841
banner             = 83C092
border-active      = A7C080
border-inactive    = 4F5B58
header             = D3C6AA
highlight          = 454545
main               = 272E33
notification       = 7FBBB3
notification-error = E67E80
subtext            = 7A8478
text               = D3C6AA

[Spicetify]
accent             = 00e089
accent-active      = 00e089
accent-inactive    = 2E2837
banner             = 00e089
border-active      = 00e089
border-inactive    = 483b5b
header             = 483b5b
highlight          = 483b5b
main               = 2E2837
notification       = 00e089
notification-error = e22134
subtext            = DEDEDE
text               = FFFFFF
